### ISSUE TITLE
Call to undefined function `ray()`

### ISSUE THREAD

**Issue by curder** [CuyZ/global-ray#2]
First of all, thanks for your work.

On my MacBook, I run the flow steps:

1. install Global-Ray
```php
composer global require cuyz/global-ray
```
2. change `php.ini`
```ini
# php.ini
auto_prepend_file=${HOME}/.composer/vendor/cuyz/global-ray/prepend_ray.php
```
3. use `ray()` in Laravel project
```php
ray('Hello world!')->blue();
```

It will throw an exception Like:

**Error**
Call to undefined function App\Http\Controllers\ray()

So I use `\ray('Hello world!')->blue();`, then also throw: Call to undefined function `ray()`.

Check php.ini config:
```
➜  ~ php -i |grep prep
auto_prepend_file => /Users/curder/.composer/vendor/cuyz/global-ray/prepend_ray.php => /Users/curder/.composer/vendor/cuyz/global-ray/prepend_ray.php
error_prepend_string => no value => no value
```

And try to restart php-fpm and nginx  services. the error also exists. 

please give me some help, thanks again.

**Comment by curder** [comment]
When I use in a signal php script, It works ok.

`index.php`

```php
<?php

ray('Hello world!')->blue();
```

<img width="700" alt="image" src="https://user-images.githubusercontent.com/8327004/113658578-e25d5c80-96d2-11eb-92ff-4cc97e2e4d5d.png">


So I think When We use some framework like Laravel, We also should install [spatie/laravel-ray](https://github.com/spatie/laravel-ray) in our project.

**Comment by romm** [comment]
Hi @curder, thanks for your report!

Indeed, when booting a Laravel app, I get the same issue using the command `php artisan serve`. Do you use Artisan as well to run your application? I'll take a look and try to understand what's wrong.

**Comment by romm** [comment]
Hello @curder,

I did some research and found out that using `php artisan serve` which under the hood runs a command like `php -S 127.0.0.1:8000 path/to/project/server.php` will result in some PHP ini configuration being skipped, which seems to be why the `auto_prepend_file` is not loaded. The strange thing is that when removing the `path/to/project/server.php` part from the command, it works.

Can I ask you what tool you use to run your application?

**Comment by curder** [comment]
> Hello @curder,
> 
> I did some research and found out that using `php artisan serve` which under the hood runs a command like `php -S 127.0.0.1:8000 path/to/project/server.php` will result in some PHP ini configuration being skipped, which seems to be why the `auto_prepend_file` is not loaded. The strange thing is that when removing the `path/to/project/server.php` part from the command, it works.
> 
> Can I ask you what tool you use to run your application?

Hi @romm 

I use valet, and also install [spatie/laravel-ray](https://github.com/spatie/laravel-ray) package in my Laravel application.

and the first example, I just run `php index.php`

**Comment by romm** [comment]
Hi @curder,

could it be that the PHP used by Valet is not the same used by CLI? Could you run `phpinfo()` on the application served by Valet and check if `auto_prepend_file` is present?

On my side I've been able to make it work with Valet, so let's try to make it work for you too. 🙂

Btw, this package currently only provides the "basic" version of Ray, but I plan to add Laravel and other frameworks versions as well in the future.

**Comment by curder** [comment]
Hi @romm 

Thanks for your response, I run `phpinfo();` in my script, and got `no value` in my Laravel project.

And I check my `php-fpm.conf` `php-fpm.d/valet-fpm.conf` and `php-fpm.d/www.conf` the is no config for `auto_prepend_file` setting.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/8327004/114296889-3061ce00-9ae0-11eb-991a-c5ab004c8ba4.png">

So I think I just config for my CLI, But fpm does not work for me, because I am not config for it.

**Comment by romm** [comment]
As a tip, running `phpinfo()` on your frontend application will tell you which `.ini` files are loaded, in one of which you should put the `auto_prepend_file` configuration.

**Comment by ghost** [comment]
@curder It works if you put the `auto_prepend_file` in a separate ini file in: `/usr/local/etc/php/7.4/conf.d/ray.ini` - change the php version number according to your version :)

**Comment by romm** [comment]
Glad to hear you managed to get it to work; actually I also put it in a separate INI file on my side.

Maybe I should add it to the doc, I'm not sure what is the behaviour of these extra files in every PHP installation though.

In the meantime I close this issue, thank you for the reporting!

**Comment by ghost** [comment]
@romm On a linux machine i would configure it in either fpm php.ini, cli or otherwise. However on a Mac (with valet) it's a little different, it didn't work for me either editing directly in the php.ini
